# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]
        package-manager: [npm, yarn]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }} and ${{ matrix.package-manager }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
    - if ${{ matrix.package-manager == 'npm'}}
    run: npm ci 
    run: npm run build --if-present
    run: npm run test
    - if ${{ matrix.package-manager == 'yarn'}}
    run: yarn
    run: yarn run build --if-present
    run: yarn run test
